# Generated by Django 5.1.1 on 2024-11-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_condition_car_fuel_type_car_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
    ]
